### ISSUE TITLE
Does not work on Ubuntu 18.04 (requires QtQuick Controls 2.5)

### ISSUE THREAD

**Issue by Tardog** [ismailof/mediacontroller_plus#1]
When opening the widget, I am greeted by the following error message:
```
org.kde.plasma.mediacontroller_plus/contents/ui/main.qml:183:34: Type ExpandedRepresentation unavailable
file:///home/xyz/.local/share/plasma/plasmoids/org.kde.plasma.mediacontroller_plus/contents/ui/ExpandedRepresentation.qml:23:1: module "QtQuick.Controls" version 2.5 is not installed
```

I already use the kubuntu-backports PPA, but apparently the required version of that module isn't there.

These are the installed packages with matching names:
https://packages.ubuntu.com/bionic/qml-module-qtquick-controls
https://packages.ubuntu.com/bionic/qml-module-qtquick-controls2

**Comment by ismailof** [comment]
I've compiled the plasmoid using ubuntu/disco, with Qt version 5.12.
It looks like minimum requirement for this version of PlasmaCore would be Qt 5.11, according to this chart: https://doc.qt.io/qt-5/qtquickcontrols-index.html#versions, which is available from cosmic and beyond.
I'll take a look at what requirements did the original plasmoid have when in bionic.

**Comment by ismailof** [comment]
Checking the differencies, they changed from using PlasmaComponents 2.0 in bionic to PlasmaComponents 3.0, which is quite a change and the dependencies bumped up a lot. I think I wouldn't be able to make a back-compatible version, sorry.

**Comment by Tardog** [comment]
Ah, that's too bad. I will be stuck with 18.04 for a while until the next LTS comes out (work laptop).

Thank you for taking the time to look into this. Since it doesn't look like it would be worth the hassle to make the widget compatible with older Qt versions, this can probably be closed.

**Comment by ismailof** [comment]
I'm closing this now, since the new kubuntu 20.04 LTS has been released.
Thank you for your patience!
