### ISSUE TITLE
REQ: Progress bar on background instead of on top

### ISSUE THREAD

**Issue by Tichy** [ismailof/mediacontroller_plus#10]
With the plasmoid placed in a panel, the progress bar is drawn on top of the cover and the song info.
Could you please place in the background, instead? That would be consistent with the task manager plasmoid behavior.
Also, while this is quite acceptable when the theme has a translucent background for the progress bar, everything is covered up with opaque themes (eg. Psion)
![Screenshot_20200415_201412](https://user-images.githubusercontent.com/2348771/79374231-7c267980-7f57-11ea-9e7e-b6b660143759.png)
![Screenshot_20200415_202614](https://user-images.githubusercontent.com/2348771/79374237-7cbf1000-7f57-11ea-98ce-46d16c1fad82.png)

**Comment by ismailof** [comment]
You're right! Uploaded now (v0.2.4) 
Thanks!
