### ISSUE TITLE
[Request] Re-enable option to display artist & title on 2 lines

### ISSUE THREAD

**Issue by GLLM** [ismailof/mediacontroller_plus#12]
Hello @ismailof !

first, thanks for this great widget. I use it in my KDE taskbar, and it's really cool !

I have one request tho, I know that in #9, you removed the 2-line display, but I would be very happy to get it back.
Indeed, I have a 27" 2160p monitor, and though I set trhe width of the display to 468px, I cannot see half of neither the artist, nor the track title.

See
![image](https://user-images.githubusercontent.com/3989573/82369771-d82d6380-9a17-11ea-9198-dff8f79575b9.png)

It'd be great if 
* the 2-line display could be an option ! 
* maybe the font size as well.
* add a scrolling feature for long titles

And the usual :
![image](https://user-images.githubusercontent.com/3989573/82369997-1c206880-9a18-11ea-9321-44c30bc5a772.png)

Many thanks,
GLLM

**Comment by ismailof** [comment]
Hi there, sorry for being idle so long and thank you for your issue.

I've been giving it a though, since the current situation is not ideal as you're screenshot shows.
I don't consider going back to two lines on a thin panel, since it was fairly impossible to make it look nice, but I'll see into implement an optional "marquee" (scrolling) when the title exceeds the widget's width.

**Comment by GLLM** [comment]
Hi @ismailof 

No pb ... a scrollee would be fine as well ... if it can be overriden with the mouse it'd be even better :)

thanks

**Comment by MurzNN** [comment]
![image](https://user-images.githubusercontent.com/336662/94394858-06117a00-0167-11eb-8eba-dc0169da8df3.png)
Here is screenshot of Media Player Compact widget (at right), that have two lines in 32px height of panel.

**Comment by ismailof** [comment]
Ok, I'm guessing they use some negative margins to go into the zone the panel reserves for itself. 
I'll take a look and maybe add it as an option

**Comment by ismailof** [comment]
I've been reworking the layout to present two lines and album art on smaller panel sizes.
![panelSize32px](https://user-images.githubusercontent.com/16477746/95629805-f0faec00-0a80-11eb-8e76-65c5884489cf.png)

The limit is now on 32px, but visuals with 30px or less are also better.
![panelSize30px](https://user-images.githubusercontent.com/16477746/95629803-f0625580-0a80-11eb-9175-726dc700412b.png)

I hope this is enough at the moment for your needs :smiley:

**Comment by Reonaydo** [comment]
There is still no multiline and Media Player Compact widget looks better. Why do You not want to make this as in Media Player Compact  ?

**Comment by ismailof** [comment]
I'm almost sure that on latest versions, there should be two lines automatically for panel heights over 28px (the exact value depends on the system's font selected), even when that meant some custom code to ignore panel margins. I'll have to check it out again.

**Comment by mattiusclay** [comment]
It'd be amazing you could make the above "28px" a setting we can change, or even better would be to add padding above/below the widget, as on my panel of .... 38px, the song title almost hits the top of the box.
