### ISSUE TITLE
Content dissapears on latte-dock panel

### ISSUE THREAD

**Issue by ismailof** [ismailof/mediacontroller_plus#2]
From kde-store.org:
>  please test it on a thin latte-dock panel. the widget is clickable but its content disappears on the panel. 

![latte_mediacontroller](https://user-images.githubusercontent.com/16477746/64707556-77768000-d4b3-11e9-926b-fb275f2813f2.gif)

**Comment by psifidotos** [comment]
what is the issue exactly in the demonstrating screenshot?

**Comment by ismailof** [comment]
You're right, that was my first try on the issue, and I thought it might be related to size values passed to the plasmoid, but it doesn't seem like it. 
The real issue is, just as the user certainly put it: the pasmoid visuals "dissapear" from latte after a few seconds, while the mouse areas and buttons are still clickable. I'm updating the summary and screenshot. 
Some hints on what can be going on, or how to debug it would be highly appreciated, thanks!

**Comment by psifidotos** [comment]
I will test it out to tell you exactly what is going on, there is a chance that it is Latte fault...

**Comment by psifidotos** [comment]
Latte fault,

fixed in upcoming 0.9.3 with: https://commits.kde.org/latte-dock/2414a918bb2dc9fd86490aa1231b0a2cf0510f52

**Comment by ismailof** [comment]
That was quick! Working great now. ευχαριστώ!
