### ISSUE TITLE
Not working on latte dock panel mode

### ISSUE THREAD

**Issue by Omanggo** [ismailof/mediacontroller_plus#7]
Mediacontroller plus only show up for a few second before disappear, but it is working quite fine on normal panel

**Comment by ismailof** [comment]
This is fixed on the new version of Latte dock 0.9.3 (https://store.kde.org/p/1169519/)
Please, update it to this version and try again.
Thanks anyway for the report. I'll probably add a note on the kde store page.

**Comment by Omanggo** [comment]
Sorry I forgot to metion that I am using Arch with Plasma 5.16,  KDE framework 5.62, QT 5.13, Latte dock version 0.9.3-1.

**Comment by Omanggo** [comment]
Never mind, it's work

**Comment by KristianUSN** [comment]
This exact same issue seems to be back on 0.10.3. Whenever I try to add the widget to any latte panel/dock it shows for a brief moment then vanishes.

**Comment by Nano-Ocelot** [comment]
> This exact same issue seems to be back on 0.10.3. Whenever I try to add the widget to any latte panel/dock it shows for a brief moment then vanishes.

Are you using 'justify' mode in lattedock and can you confirm that opening the editing page for the panel and closing it fixes the issue?

**Comment by KristianUSN** [comment]
> > This exact same issue seems to be back on 0.10.3. Whenever I try to add the widget to any latte panel/dock it shows for a brief moment then vanishes.
> 
> Are you using 'justify' mode in lattedock and can you confirm that opening the editing page for the panel and closing it fixes the issue?

Yes, I tried a myriad of settings and nothing makes it appear. I also tried to place it in the regular latte dock but it just vanishes. The only thing I've noticed is that it seems to still exist on the panel/dock. One time when I clicked on the workspace switcher widget the media controller+ pop up appeared.

**Comment by AustinMcCallister** [comment]
Just came here to say that I too am having problems with this widget in panel mode. Unlike the above poster, mine will not go in the panel at all. Widget itself works fine on plasma desktop. I'm using 10.4 from the main arch repo.
