### ISSUE TITLE
How i can make it transparent?

### ISSUE THREAD

**Issue by RezaSh13** [ismailof/mediacontroller_plus#8]
How i can make media controller plus transparent like clock in the photo?
![image](https://user-images.githubusercontent.com/22277992/73608006-ac09e600-45d2-11ea-8b51-e1fc0542c144.png)

**Comment by ismailof** [comment]
Hi! Thanks for posting your issue.

In Plasma 5.18 there is a new mechanism that shows a button you can press to hide the background. I've updated the code of the widget to use that mechanism:
![mc+_showbackground](https://user-images.githubusercontent.com/16477746/73611807-ff396400-45e5-11ea-9731-2c04a8fac93f.png)

But of course, it will only work after 5.18.
