### ISSUE TITLE
compact view on thin panel

### ISSUE THREAD

**Issue by grachevmikh** [ismailof/mediacontroller_plus#9]
Hi, maybe add settings for line spacing? or where i can change this?
![Screenshot_20200209_183015](https://user-images.githubusercontent.com/44836178/74101317-083caf00-4b6b-11ea-94de-1829bfa32f61.png)

**Comment by ismailof** [comment]
For thin panels, it didn't look right even with less spacing, so I've compacted it in one line:
![media_minimalview](https://user-images.githubusercontent.com/16477746/74110439-f53ad680-4b8c-11ea-9f7c-6e7e50682ae7.png)
I hope it fits your needs.
